import HeroImage from "../assets/banner-stack.png";

export const Hero = () => {
  return (
    <section className="hero container mx-auto px-4 sm:px-6 lg:px-8">
      <div
        className="
          flex
          flex-col
          lg:flex-row
          justify-between
          items-center
          gap-8
          lg:gap-0
        "
      >
        <div
          className="
            information
            w-full
            lg:w-1/2
            text-center
            lg:text-left
          "
        >
          <h1
            className="
              text-[28px]
              sm:text-[40px]
              lg:text-[60px]
              leading-tight
              m-0
              p-0
              text-heading
              font-inter
              font-extrabold
            "
          >
            Build Your Ideal
          </h1>
          <h2
            className="
              text-[28px]
              sm:text-[40px]
              lg:text-[60px]
              leading-tight
              lg:leading-14
              m-0
              p-0
              gradient-text
              font-inter
              font-extrabold
            "
          >
            Development Stack
          </h2>

          <p
            className="
              text-[11px]
              sm:text-sm
              lg:text-lg
              leading-5
              sm:leading-6
              lg:leading-7
              w-full
              lg:w-142.5
              max-w-xl
              mx-auto
              lg:mx-0
              mt-3
              mb-6
              lg:mb-10
              text-text
              font-jakarta
            "
          >
            Explore frontend, backend, database, and tooling options, compare
            them side by side, and put together the stack that fits your next
            project.
          </p>
          <div
            className="
              btn
              flex
              justify-center
              lg:justify-start
              gap-2
              sm:gap-3
            "
          >
            <button
              className="
                gradient-background
                cursor-pointer
                text-white
                font-inter
                font-semibold
                text-[9px]
                sm:text-xs
                lg:text-sm
                py-2
                sm:py-2.5
                lg:py-3
                px-4
                sm:px-7
                lg:px-11
                rounded-lg
                sm:rounded-xl
              "
            >
              Explore Technologies
            </button>
            <button
              className="
                text-text
                font-inter
                text-[9px]
                sm:text-xs
                lg:text-sm
                py-2
                sm:py-2.5
                lg:py-3
                px-4
                sm:px-7
                lg:px-11
                rounded-lg
                sm:rounded-xl
                border
                border-[#E5E7EB]
                gradient-background-hover
                hover:text-white
                cursor-pointer
                transition
              "
            >
              Learn More
            </button>
          </div>
        </div>
        <div
          className="
            image
            w-full
            lg:w-1/2
            flex
            justify-center
            lg:justify-end
          "
        >
          <img
            src={HeroImage}
            alt="Development stack"
            className="
              w-[85%]
              sm:w-[70%]
              md:w-[60%]
              lg:w-full
              max-w-125
              object-contain
            "
          />
        </div>
      </div>
    </section>
  );
};
